- name: Copy SSL certificate
  become: true
  copy:
    src: "{{ ssl_certificate_path }}"
    dest: /etc/ssl/certs/origin.pem
    mode: 0644

- name: Copy SSL private key
  become: true
  copy:
    src: "{{ ssl_private_key_path }}"
    dest: /etc/ssl/certs/privkey.pem
    mode: 0600
