- name: Install Docker
  become: true
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: true

- name: Ensure Docker service is running
  become: true
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
