- name: Copy SCP script to target
  template:
    src: fetch_files.sh.j2
    dest: /usr/local/bin/fetch_files.sh
    mode: "0755"
    owner: "{{ backup_user }}"
    group: "{{ backup_user }}"
  become: true

- name: Copy systemd service file to target
  template:
    src: fetch_files.service.j2
    dest: /etc/systemd/system/fetch_files.service
  become: true

- name: Copy systemd timer file to target
  template:
    src: fetch_files.timer.j2
    dest: /etc/systemd/system/fetch_files.timer
  become: true

- name: Reload systemd daemon to recognize new service
  systemd:
    daemon_reload: yes
  become: true

- name: Enable and start fetch_files timer
  systemd:
    name: fetch_files.timer
    enabled: yes
    state: started
  become: true
