- name: Copy public SSH key from host to control node
  hosts: webserver
  vars_files:
    - "./vault.yml"
  vars:
    ansible_user: "{{ become_credentials['webserver']['user'] }}"
    ansible_become_password: "{{ become_credentials['webserver']['password'] }}"
  roles:
    - copy_public_ssh_key

- name: Configure backup server
  hosts: backup_server
  vars_files:
    - "./vault.yml"
  vars:
    ansible_user: "{{ become_credentials['backupserver']['user'] }}"
    ansible_become_password: "{{ become_credentials['backupserver']['password'] }}"
  roles:
    - common
    - configure_backup_scp_auth
    - directory_counter_cleaner
