- name: Home Assistant
  hosts: webserver
  vars_files:
    - "./vault.yml"
  vars:
    ansible_user: "{{ become_credentials['webserver']['user'] }}"
    ansible_become_password: "{{ become_credentials['webserver']['password'] }}"
  roles:
    - common
    - copy_public_ssh_key
    - homeassistant_backup_service
    - setup_ssl
    - install_docker
    - run_containers
